#!/bin/bash
ARCH=$(sysctl hw.optional.arm64 2>/dev/null | cut -c 20-) ; [[ "$ARCH" = "1" ]] && export ARCH=arm64 || export ARCH=x86_64
export PICON_HOME="/Applications/PiCon.app/Contents/Resources"
export PATH="$PICON_HOME/$ARCH/bin:$PATH"
export LIMA_HOME="$PICON_HOME/lima"
limactl stop -f
limactl --debug start
sleep 1
until cat /private/tmp/picon.log | grep READY > /dev/null; do sleep 1; done
lima sudo hostname $(hostname -s)-pihole
while true; do pidof qemu ; sleep 3600 ; done
